vich_uploader:
    db_driver: orm

    mappings:
        images_directory:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'

        partner_image:
            uri_prefix: /uploads/partners
            upload_destination: '%kernel.project_dir%/public/uploads/partners'

        user_video:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/videos'

        #new_directory:
        #    uri_prefix: /uploads
              #  upload_destination: '%kernel.project_dir%/public/uploads/images'





