<?php

namespace App\Form;

use App\Classe\SearchMembre;


use App\Entity\Partner;
use App\Repository\PartnerRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchMembreType extends AbstractType
{
	private $partnerRepository;

	public function __construct(PartnerRepository $partnerRepository)
	{
		$this->partnerRepository = $partnerRepository;
	}

	//creation du formulaire
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
//            ->add('string', TextType::class, [
//                'label' =>false,
//                'required' => false,
//                'attr' => [
//                    'placeholder' => 'Votre recherche...',
//                    'class'=>'form-control-sm'
//                ]
//            ])
			->add('partner', EntityType::class, [
				'label' => 'Partenaire',
				'required' => false,
				'placeholder' => 'Choisissez un partenaire',
				'choice_label' => 'content',
				'class' => Partner::class,
				'mapped' => false
			]);
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(['csrf_protection' => false]);
	}

	//fonction
	public function getBlockPrefix()
	{
		return ''; //parent::getBlockPrefix(); // TODO: Change the autogenerated stub
	}
}
